#!/usr/bin/env node
/**
 * Seeds a fully-populated MoodSync demo account, for showing the product
 * when no real wearable/smart-home account is connected.
 *
 * WHAT THIS DATA IS: simulated. Every row this writes is generated by the
 * curve functions below — it is NOT real biometric data from a real
 * person, and no automation listed here ever actually dimmed a real
 * light. The point is to exercise the real schema and the real read paths
 * (every screen queries these tables normally, with no demo-mode branch
 * anywhere in the app) so the UI can be shown populated rather than
 * empty. Keep the labelling honest when demoing: this is a seeded
 * account, not a case study, and the recovery arc below is illustrative,
 * not evidence that MoodSync improved anyone's recovery.
 *
 * WHY DIRECT PRISMA RATHER THAN THE API (unlike scripts/demoAppleHealthSync.mjs,
 * which deliberately goes through the real ingest endpoint): most of what
 * makes the app look alive — execution history, insights, notifications,
 * recommendations — has no public write endpoint at all. Those rows are
 * normally produced by the dispatch engine reacting to live provider data
 * over days. Seeding them means writing them directly.
 *
 * The 14-day arc is shaped so the charts tell a story instead of showing
 * noise: a settled baseline, a rough mid-period stretch (poor sleep,
 * elevated resting HR, low recovery), then a return toward baseline.
 *
 * Usage:
 *   node scripts/seedDemoAccount.mjs [--email x] [--password y] [--reset]
 *
 * Defaults to demo@moodsync.app / MoodSyncDemo!2026. `--reset` wipes the
 * demo user's existing rows first (safe to re-run; only ever touches the
 * one demo account, never other users).
 *
 * Requires DATABASE_URL — run it the same way the backend is run, e.g.
 *   node --env-file=backend/.env.local scripts/seedDemoAccount.mjs --reset
 */

import { PrismaClient } from '@prisma/client';
import { hash } from '@node-rs/argon2';

const args = process.argv.slice(2);
function arg(name, fallback) {
  const i = args.indexOf(`--${name}`);
  return i !== -1 && args[i + 1] ? args[i + 1] : fallback;
}

const EMAIL = arg('email', 'demo@moodsync.app');
const PASSWORD = arg('password', 'MoodSyncDemo!2026');
const RESET = args.includes('--reset');
const DAYS = 14;

// Matches backend/src/auth/password.ts exactly — a hash written with
// different parameters still verifies, but keeping these in sync means
// the demo account is indistinguishable from a real signup.
const HASH_OPTIONS = { memoryCost: 19456, timeCost: 2, parallelism: 1 };

const prisma = new PrismaClient();

/** Day 0 = 13 days ago, day 13 = today. */
function dayStart(dayIndex) {
  const d = new Date();
  d.setHours(0, 0, 0, 0);
  d.setDate(d.getDate() - (DAYS - 1 - dayIndex));
  return d;
}

function at(dayIndex, hour, minute = 0) {
  const d = dayStart(dayIndex);
  d.setHours(hour, minute, 0, 0);
  return d;
}

const round = (n, dp = 0) => Number(n.toFixed(dp));

/**
 * The narrative arc, as a 0..1 "strain" factor per day: low is settled,
 * high is the rough stretch. Days 6-9 are the difficult window; 10-13
 * ease back down. Every metric below is derived from this one curve so
 * the charts stay internally consistent (bad sleep night == low recovery
 * morning == higher resting HR), which is what makes seeded data read as
 * plausible rather than random.
 */
function strainFor(day) {
  const curve = [0.15, 0.2, 0.12, 0.25, 0.3, 0.45, 0.75, 0.85, 0.9, 0.7, 0.45, 0.3, 0.2, 0.15];
  return curve[day] ?? 0.3;
}

/** Small deterministic wobble so values aren't suspiciously smooth. */
function jitter(day, salt, magnitude) {
  const x = Math.sin((day + 1) * salt) * 10000;
  return (x - Math.floor(x) - 0.5) * 2 * magnitude;
}

function readingForDay(day) {
  const s = strainFor(day);

  const recoveryScore = clamp(round(88 - s * 52 + jitter(day, 12.9898, 4)), 5, 99);
  const sleepScore = clamp(round(90 - s * 45 + jitter(day, 78.233, 5)), 5, 99);
  const restingHeartRate = clamp(round(52 + s * 13 + jitter(day, 43.11, 1.5)), 44, 78);
  const heartRate = clamp(round(64 + s * 18 + jitter(day, 91.7, 3)), 50, 105);
  const stressLevel = clamp(round(22 + s * 55 + jitter(day, 33.7, 5)), 5, 95);
  const activityLevel = clamp(round(58 - s * 20 + jitter(day, 55.3, 12)), 10, 95);
  const steps = clamp(Math.round(9200 - s * 3400 + jitter(day, 71.2, 1200)), 1200, 18000);
  const calories = clamp(round(2350 - s * 260 + jitter(day, 22.4, 140)), 1400, 3600);

  // Sleep stages: total sleep shrinks on high-strain nights, and deep
  // sleep is hit proportionally harder than light — the pattern the
  // WHOOP/Fitbit stage summaries actually show. Minutes are kept
  // self-consistent (deep + rem + light ~= total in bed asleep).
  const totalSleepMinutes = clamp(Math.round(455 - s * 105 + jitter(day, 61.8, 18)), 240, 540);
  const deepSleepMinutes = clamp(Math.round(totalSleepMinutes * (0.22 - s * 0.07)), 25, 150);
  const remSleepMinutes = clamp(Math.round(totalSleepMinutes * (0.23 - s * 0.03)), 30, 160);
  const lightSleepMinutes = clamp(totalSleepMinutes - deepSleepMinutes - remSleepMinutes, 60, 400);

  return {
    recoveryScore,
    sleepScore,
    restingHeartRate,
    heartRate,
    stressLevel,
    activityLevel,
    steps,
    calories,
    deepSleepMinutes,
    remSleepMinutes,
    lightSleepMinutes,
  };
}

function clamp(n, lo, hi) {
  return Math.min(hi, Math.max(lo, n));
}

async function main() {
  console.log(`Seeding demo account: ${EMAIL}`);

  const passwordHash = await hash(PASSWORD, HASH_OPTIONS);

  const user = await prisma.user.upsert({
    where: { email: EMAIL },
    update: { passwordHash, displayName: 'Alex Rivera', timezone: 'America/Los_Angeles' },
    create: {
      email: EMAIL,
      passwordHash,
      displayName: 'Alex Rivera',
      timezone: 'America/Los_Angeles',
    },
  });

  if (RESET) {
    // Order matters only where a cascade doesn't already cover it; the
    // connection deletes cascade to ConnectedDevice and OAuthToken is
    // SetNull, so no orphan cleanup is needed beyond this.
    await prisma.$transaction([
      prisma.automationExecutionLog.deleteMany({ where: { userId: user.id } }),
      prisma.notification.deleteMany({ where: { userId: user.id } }),
      prisma.recommendation.deleteMany({ where: { userId: user.id } }),
      prisma.insight.deleteMany({ where: { userId: user.id } }),
      prisma.meditationSession.deleteMany({ where: { userId: user.id } }),
      prisma.biometricReading.deleteMany({ where: { userId: user.id } }),
      prisma.automationRule.deleteMany({ where: { userId: user.id } }),
      prisma.smartHomeConnection.deleteMany({ where: { userId: user.id } }),
      prisma.wearableConnection.deleteMany({ where: { userId: user.id } }),
    ]);
    console.log('  reset: cleared existing demo rows');
  }

  await prisma.userPreferences.upsert({
    where: { userId: user.id },
    update: {},
    create: { userId: user.id, notificationsEnabled: true, automationsEnabled: true },
  });

  // --- Connections -------------------------------------------------------
  // status ACTIVE with no oauthTokenId: these are display-only demo
  // connections. Nothing will actually sync from them (there are no
  // credentials), which is correct — the readings below are seeded
  // directly rather than pulled.
  const whoop = await prisma.wearableConnection.upsert({
    where: { userId_provider: { userId: user.id, provider: 'WHOOP' } },
    update: { status: 'ACTIVE', lastSyncedAt: new Date(Date.now() - 8 * 60 * 1000) },
    create: {
      userId: user.id,
      provider: 'WHOOP',
      status: 'ACTIVE',
      providerUserId: 'demo-whoop-user',
      deviceName: 'WHOOP 4.0',
      lastSyncedAt: new Date(Date.now() - 8 * 60 * 1000),
    },
  });

  await prisma.wearableConnection.upsert({
    where: { userId_provider: { userId: user.id, provider: 'APPLE_HEALTH' } },
    update: { status: 'ACTIVE', lastSyncedAt: new Date(Date.now() - 21 * 60 * 1000) },
    create: {
      userId: user.id,
      provider: 'APPLE_HEALTH',
      status: 'ACTIVE',
      deviceName: 'Apple Watch Series 9',
      lastSyncedAt: new Date(Date.now() - 21 * 60 * 1000),
    },
  });

  const hue = await prisma.smartHomeConnection.upsert({
    where: { userId_provider: { userId: user.id, provider: 'HUE' } },
    update: { status: 'ACTIVE', lastSyncedAt: new Date(Date.now() - 12 * 60 * 1000) },
    create: {
      userId: user.id,
      provider: 'HUE',
      status: 'ACTIVE',
      providerAccountId: 'demo-hue-bridge',
      metadata: { bridgeId: 'demo-bridge-001' },
      lastSyncedAt: new Date(Date.now() - 12 * 60 * 1000),
    },
  });

  await prisma.smartHomeConnection.upsert({
    where: { userId_provider: { userId: user.id, provider: 'SPOTIFY' } },
    update: { status: 'ACTIVE', lastSyncedAt: new Date(Date.now() - 35 * 60 * 1000) },
    create: {
      userId: user.id,
      provider: 'SPOTIFY',
      status: 'ACTIVE',
      providerAccountId: 'demo-spotify-user',
      metadata: {},
      lastSyncedAt: new Date(Date.now() - 35 * 60 * 1000),
    },
  });

  const devices = [
    { externalDeviceId: 'hue-1', name: 'Bedroom Ceiling', deviceType: 'light', room: 'Bedroom' },
    { externalDeviceId: 'hue-2', name: 'Bedside Lamp', deviceType: 'light', room: 'Bedroom' },
    { externalDeviceId: 'hue-3', name: 'Desk Strip', deviceType: 'light', room: 'Office' },
    { externalDeviceId: 'hue-4', name: 'Living Room Floor', deviceType: 'light', room: 'Living room' },
  ];
  for (const d of devices) {
    await prisma.connectedDevice.upsert({
      where: {
        smartHomeConnectionId_externalDeviceId: {
          smartHomeConnectionId: hue.id,
          externalDeviceId: d.externalDeviceId,
        },
      },
      update: { ...d, isOnline: true },
      create: { ...d, smartHomeConnectionId: hue.id, isOnline: true },
    });
  }
  console.log(`  connections: 2 wearable, 2 smart home, ${devices.length} devices`);

  // --- Biometric readings ------------------------------------------------
  // Two readings per day: a morning one carrying the overnight sleep +
  // recovery figures (how WHOOP actually reports — a recovery score is a
  // once-per-morning value, not a continuous stream), and an evening one
  // carrying that day's activity.
  const readingRows = [];
  for (let day = 0; day < DAYS; day++) {
    const r = readingForDay(day);
    readingRows.push({
      userId: user.id,
      provider: 'WHOOP',
      timestamp: at(day, 7, 15),
      recoveryScore: r.recoveryScore,
      sleepScore: r.sleepScore,
      restingHeartRate: r.restingHeartRate,
      heartRate: r.restingHeartRate + 6,
      stressLevel: r.stressLevel,
      deepSleepMinutes: r.deepSleepMinutes,
      remSleepMinutes: r.remSleepMinutes,
      lightSleepMinutes: r.lightSleepMinutes,
    });
    readingRows.push({
      userId: user.id,
      provider: 'APPLE_HEALTH',
      timestamp: at(day, 19, 30),
      heartRate: r.heartRate,
      restingHeartRate: r.restingHeartRate,
      activityLevel: r.activityLevel,
      steps: r.steps,
      calories: r.calories,
      stressLevel: r.stressLevel,
      heartRateVariability: clamp(round(62 - strainFor(day) * 24 + jitter(day, 17.3, 4), 1), 18, 95),
      respiratoryRate: clamp(round(14.5 + strainFor(day) * 2.2 + jitter(day, 88.1, 0.4), 1), 11, 20),
      bloodOxygen: clamp(round(97.5 - strainFor(day) * 1.2 + jitter(day, 29.6, 0.3), 1), 93, 100),
    });
  }
  // Intraday heart-rate samples for the last two days. Without these the
  // "last N readings" charts (which plot individual samples, not daily
  // rollups) have only one point per day to draw and render as a nearly
  // flat line — a real-looking gap, since Apple Health and Fitbit both
  // genuinely deliver sample-level HR on a minutes cadence.
  for (let day = DAYS - 2; day < DAYS; day++) {
    const base = readingForDay(day);
    for (let slot = 0; slot < 12; slot++) {
      const hour = 8 + slot; // 08:00–19:00
      if (day === DAYS - 1 && hour > new Date().getHours()) break; // don't post-date today
      // A gentle diurnal curve: lowest early, peaking late afternoon.
      const diurnal = Math.sin(((hour - 6) / 16) * Math.PI) * 12;
      readingRows.push({
        userId: user.id,
        provider: 'APPLE_HEALTH',
        timestamp: at(day, hour, 5),
        heartRate: clamp(round(base.restingHeartRate + 8 + diurnal + jitter(day * 24 + hour, 13.7, 4)), 48, 130),
        restingHeartRate: base.restingHeartRate,
      });
    }
  }

  await prisma.biometricReading.createMany({ data: readingRows, skipDuplicates: true });
  console.log(`  biometrics: ${readingRows.length} readings across ${DAYS} days (incl. intraday HR samples)`);

  // --- Automation rules --------------------------------------------------
  // Shapes match shared/src/automation.ts (RuleCondition[] / AutomationAction[])
  // and mirror the real templates in frontend/src/lib/ruleTemplates.ts.
  const ruleSpecs = [
    {
      name: 'Elevated Stress',
      conditions: [{ field: 'heartRate', operator: 'gt', value: 95 }],
      actions: [
        { type: 'hue.set_color_temperature', provider: 'hue', params: { deviceId: 'hue-1', mirek: 450 } },
      ],
      cooldownMinutes: 30,
      priority: 70,
      timeWindow: null,
    },
    {
      name: 'Focus Mode',
      conditions: [],
      actions: [
        { type: 'hue.set_color_temperature', provider: 'hue', params: { deviceId: 'hue-3', mirek: 250 } },
      ],
      cooldownMinutes: 60,
      priority: 50,
      timeWindow: { start: '09:00', end: '17:00' },
    },
    {
      name: 'Sleep Preparation',
      conditions: [],
      actions: [
        { type: 'hue.set_color_temperature', provider: 'hue', params: { deviceId: 'hue-2', mirek: 454 } },
        { type: 'spotify.play_playlist', provider: 'spotify', params: { playlistUri: 'spotify:playlist:37i9dQZF1DWZd79rJ6a7lp' } },
      ],
      cooldownMinutes: 1440,
      priority: 80,
      timeWindow: { start: '21:30', end: '22:30' },
    },
    {
      name: 'Low Recovery — ease the morning',
      conditions: [{ field: 'wellness.recovery', operator: 'lt', value: 40 }],
      actions: [
        { type: 'hue.set_brightness', provider: 'hue', params: { deviceId: 'hue-1', brightness: 35 } },
      ],
      cooldownMinutes: 720,
      priority: 65,
      timeWindow: null,
    },
    {
      name: 'Workout',
      conditions: [{ field: 'heartRate', operator: 'gt', value: 120 }],
      actions: [
        { type: 'hue.set_brightness', provider: 'hue', params: { deviceId: 'hue-4', brightness: 100 } },
      ],
      cooldownMinutes: 20,
      priority: 70,
      timeWindow: null,
      enabled: false,
    },
  ];

  const rules = [];
  for (const spec of ruleSpecs) {
    const { enabled = true, ...rest } = spec;
    rules.push(
      await prisma.automationRule.create({
        data: { userId: user.id, enabled, ...rest },
      }),
    );
  }
  console.log(`  rules: ${rules.length} (${rules.filter((r) => r.enabled).length} enabled)`);

  // --- Execution history + notifications ---------------------------------
  // Firings cluster in the high-strain window, which is what makes the
  // history feel causally connected to the biometrics above rather than
  // sprinkled at random.
  const logs = [];
  const notifications = [];
  for (let day = 0; day < DAYS; day++) {
    const s = strainFor(day);

    // Sleep Preparation runs nightly (schedule-triggered, no condition).
    logs.push({
      userId: user.id,
      ruleId: rules[2].id,
      outcome: 'EXECUTED',
      reason: 'Time window 21:30–22:30 matched; dimmed Bedside Lamp to 454 mirek and started wind-down playlist.',
      executedAt: at(day, 21, 34),
    });

    // Focus Mode on weekdays.
    const weekday = dayStart(day).getDay();
    if (weekday !== 0 && weekday !== 6) {
      logs.push({
        userId: user.id,
        ruleId: rules[1].id,
        outcome: 'EXECUTED',
        reason: 'Time window 09:00–17:00 matched; set Desk Strip to 250 mirek.',
        executedAt: at(day, 9, 12),
      });
    }

    // Elevated Stress fires on the hard days.
    if (s >= 0.6) {
      logs.push({
        userId: user.id,
        ruleId: rules[0].id,
        outcome: 'EXECUTED',
        reason: `Heart rate ${readingForDay(day).heartRate} bpm exceeded threshold 95; warmed Bedroom Ceiling to 450 mirek.`,
        executedAt: at(day, 15, 40),
      });
      notifications.push({
        userId: user.id,
        ruleId: rules[0].id,
        title: 'Elevated Stress',
        body: `Your heart rate hit ${readingForDay(day).heartRate} bpm — MoodSync warmed your lights to help you settle.`,
        createdAt: at(day, 15, 41),
        readAt: day < DAYS - 3 ? at(day, 18, 0) : null,
      });
    }

    // Low Recovery on the worst mornings.
    if (readingForDay(day).recoveryScore < 40) {
      logs.push({
        userId: user.id,
        ruleId: rules[3].id,
        outcome: 'EXECUTED',
        reason: `Recovery ${readingForDay(day).recoveryScore} below threshold 40; kept Bedroom Ceiling at 35% for a gentler start.`,
        executedAt: at(day, 7, 22),
      });
    }

    // One realistic cooldown skip, so the history isn't uniformly successful.
    if (s >= 0.85) {
      logs.push({
        userId: user.id,
        ruleId: rules[0].id,
        outcome: 'SKIPPED_COOLDOWN',
        reason: 'Rule fired 12 minutes ago; 30-minute cooldown still active.',
        executedAt: at(day, 15, 52),
      });
    }
  }
  await prisma.automationExecutionLog.createMany({ data: logs });
  await prisma.notification.createMany({ data: notifications });
  console.log(`  history: ${logs.length} executions, ${notifications.length} notifications`);

  // --- Recommendations ---------------------------------------------------
  // suggestedActions is { templateId } pointing at a real
  // frontend/src/lib/ruleTemplates.ts entry — matching what
  // ai/src/recommendations.ts actually emits.
  await prisma.recommendation.createMany({
    data: [
      {
        userId: user.id,
        title: 'Add a Wake Up routine',
        description:
          'Your recovery dipped below 40 on three mornings in the last two weeks. A gradual brightness ramp between 06:00 and 08:00 tends to make low-recovery mornings easier.',
        suggestedActions: { templateId: 'wake-up' },
        status: 'PENDING',
        createdAt: at(DAYS - 2, 8, 5),
      },
      {
        userId: user.id,
        title: 'Your Workout rule is switched off',
        description:
          'You have a Workout rule configured but disabled. Your activity level averaged 58 over the last fortnight — turning it back on would light the living room when your heart rate passes 120.',
        suggestedActions: { templateId: 'workout' },
        status: 'PENDING',
        createdAt: at(DAYS - 1, 11, 20),
      },
    ],
  });

  // --- Insights ----------------------------------------------------------
  const thisWeekStart = dayStart(DAYS - 7);
  const lastWeekStart = dayStart(DAYS - 14);
  const avg = (from, to, key) => {
    let sum = 0;
    for (let d = from; d < to; d++) sum += readingForDay(d)[key];
    return round(sum / (to - from), 1);
  };

  await prisma.insight.createMany({
    data: [
      {
        userId: user.id,
        period: 'WEEKLY',
        metric: 'recoveryScore',
        periodStart: thisWeekStart,
        periodEnd: dayStart(DAYS - 1),
        value: avg(7, 14, 'recoveryScore'),
        trend: round(avg(7, 14, 'recoveryScore') - avg(0, 7, 'recoveryScore'), 1),
        summary: 'Recovery averaged higher this week than last, with the biggest gains in the last three days.',
      },
      {
        userId: user.id,
        period: 'WEEKLY',
        metric: 'sleepScore',
        periodStart: thisWeekStart,
        periodEnd: dayStart(DAYS - 1),
        value: avg(7, 14, 'sleepScore'),
        trend: round(avg(7, 14, 'sleepScore') - avg(0, 7, 'sleepScore'), 1),
        summary: 'Sleep scores recovered after a difficult mid-period stretch.',
      },
      {
        userId: user.id,
        period: 'WEEKLY',
        metric: 'restingHeartRate',
        periodStart: lastWeekStart,
        periodEnd: thisWeekStart,
        value: avg(0, 7, 'restingHeartRate'),
        trend: round(avg(0, 7, 'restingHeartRate') - avg(7, 14, 'restingHeartRate'), 1),
        summary: 'Resting heart rate climbed during the high-strain window, then settled.',
      },
    ],
  });
  console.log('  insights + recommendations written');

  // --- Meditation sessions -----------------------------------------------
  const sessions = [];
  for (const [day, minutes, ambience] of [
    [DAYS - 9, 10, 'rain'],
    [DAYS - 7, 15, 'forest'],
    [DAYS - 5, 5, 'silence'],
    [DAYS - 3, 15, 'rain'],
    [DAYS - 2, 20, 'ocean'],
    [DAYS - 1, 10, 'forest'],
  ]) {
    sessions.push({
      userId: user.id,
      durationMinutes: minutes,
      ambience,
      startedAt: at(day, 20, 10),
      completedAt: at(day, 20, 10 + minutes),
    });
  }
  await prisma.meditationSession.createMany({ data: sessions });
  console.log(`  meditation: ${sessions.length} sessions`);

  console.log(`\nDone. Sign in with:\n  ${EMAIL}\n  ${PASSWORD}\n`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
